/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductOutput,
} from '../models';
import {
    ProductOutputFromJSON,
    ProductOutputToJSON,
} from '../models';

export interface GetProductsRequest {
    xFitToken?: string | null;
}

/**
 * 
 */
export class ProductControllerApi extends runtime.BaseAPI {

    /**
     */
    async getProductsRaw(requestParameters: GetProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductOutput>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xFitToken !== undefined && requestParameters.xFitToken !== null) {
            headerParameters['x-fit-token'] = String(requestParameters.xFitToken);
        }

        const response = await this.request({
            path: `/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductOutputFromJSON));
    }

    /**
     */
    async getProducts(requestParameters: GetProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductOutput>> {
        const response = await this.getProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
