/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CancelReasonInput = {
    Customer: 'CUSTOMER',
    Fraud: 'FRAUD',
    Inventory: 'INVENTORY',
    Declined: 'DECLINED',
    Other: 'OTHER'
} as const;
export type CancelReasonInput = typeof CancelReasonInput[keyof typeof CancelReasonInput];


export function CancelReasonInputFromJSON(json: any): CancelReasonInput {
    return CancelReasonInputFromJSONTyped(json, false);
}

export function CancelReasonInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelReasonInput {
    return json as CancelReasonInput;
}

export function CancelReasonInputToJSON(value?: CancelReasonInput | null): any {
    return value as any;
}

