/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CancelReasonOutput = {
    Null: 'NULL',
    Customer: 'CUSTOMER',
    Fraud: 'FRAUD',
    Inventory: 'INVENTORY',
    Declined: 'DECLINED',
    Other: 'OTHER'
} as const;
export type CancelReasonOutput = typeof CancelReasonOutput[keyof typeof CancelReasonOutput];


export function CancelReasonOutputFromJSON(json: any): CancelReasonOutput {
    return CancelReasonOutputFromJSONTyped(json, false);
}

export function CancelReasonOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelReasonOutput {
    return json as CancelReasonOutput;
}

export function CancelReasonOutputToJSON(value?: CancelReasonOutput | null): any {
    return value as any;
}

