/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerInput
 */
export interface CustomerInput {
    /**
     * 
     * @type {number}
     * @memberof CustomerInput
     */
    id: number;
}

/**
 * Check if a given object implements the CustomerInput interface.
 */
export function instanceOfCustomerInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CustomerInputFromJSON(json: any): CustomerInput {
    return CustomerInputFromJSONTyped(json, false);
}

export function CustomerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CustomerInputToJSON(value?: CustomerInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

