/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FinancialStatusInput = {
    Pending: 'PENDING',
    Authorized: 'AUTHORIZED',
    PartiallyPaid: 'PARTIALLY_PAID',
    Paid: 'PAID',
    PartiallyRefunded: 'PARTIALLY_REFUNDED',
    Refunded: 'REFUNDED',
    Voided: 'VOIDED'
} as const;
export type FinancialStatusInput = typeof FinancialStatusInput[keyof typeof FinancialStatusInput];


export function FinancialStatusInputFromJSON(json: any): FinancialStatusInput {
    return FinancialStatusInputFromJSONTyped(json, false);
}

export function FinancialStatusInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatusInput {
    return json as FinancialStatusInput;
}

export function FinancialStatusInputToJSON(value?: FinancialStatusInput | null): any {
    return value as any;
}

