/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FinancialStatusOutput = {
    Null: 'NULL',
    Pending: 'PENDING',
    Authorized: 'AUTHORIZED',
    PartiallyPaid: 'PARTIALLY_PAID',
    Paid: 'PAID',
    PartiallyRefunded: 'PARTIALLY_REFUNDED',
    Refunded: 'REFUNDED',
    Voided: 'VOIDED'
} as const;
export type FinancialStatusOutput = typeof FinancialStatusOutput[keyof typeof FinancialStatusOutput];


export function FinancialStatusOutputFromJSON(json: any): FinancialStatusOutput {
    return FinancialStatusOutputFromJSONTyped(json, false);
}

export function FinancialStatusOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialStatusOutput {
    return json as FinancialStatusOutput;
}

export function FinancialStatusOutputToJSON(value?: FinancialStatusOutput | null): any {
    return value as any;
}

