/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FulfillmentStatus = {
    Null: 'NULL',
    Fulfilled: 'FULFILLED',
    Partial: 'PARTIAL',
    Restocked: 'RESTOCKED',
    Pending: 'PENDING'
} as const;
export type FulfillmentStatus = typeof FulfillmentStatus[keyof typeof FulfillmentStatus];


export function FulfillmentStatusFromJSON(json: any): FulfillmentStatus {
    return FulfillmentStatusFromJSONTyped(json, false);
}

export function FulfillmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentStatus {
    return json as FulfillmentStatus;
}

export function FulfillmentStatusToJSON(value?: FulfillmentStatus | null): any {
    return value as any;
}

