/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FulfillmentStatusOutput = {
    Null: 'NULL',
    Fulfilled: 'FULFILLED',
    Partial: 'PARTIAL',
    Restocked: 'RESTOCKED',
    Pending: 'PENDING'
} as const;
export type FulfillmentStatusOutput = typeof FulfillmentStatusOutput[keyof typeof FulfillmentStatusOutput];


export function FulfillmentStatusOutputFromJSON(json: any): FulfillmentStatusOutput {
    return FulfillmentStatusOutputFromJSONTyped(json, false);
}

export function FulfillmentStatusOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentStatusOutput {
    return json as FulfillmentStatusOutput;
}

export function FulfillmentStatusOutputToJSON(value?: FulfillmentStatusOutput | null): any {
    return value as any;
}

