/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyInput
 */
export interface MoneyInput {
    /**
     * 
     * @type {number}
     * @memberof MoneyInput
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof MoneyInput
     */
    currencyCode: string;
}

/**
 * Check if a given object implements the MoneyInput interface.
 */
export function instanceOfMoneyInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "currencyCode" in value;

    return isInstance;
}

export function MoneyInputFromJSON(json: any): MoneyInput {
    return MoneyInputFromJSONTyped(json, false);
}

export function MoneyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currencyCode': json['currency_code'],
    };
}

export function MoneyInputToJSON(value?: MoneyInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency_code': value.currencyCode,
    };
}

