/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PriceSetInput } from './PriceSetInput';
import {
    PriceSetInputFromJSON,
    PriceSetInputFromJSONTyped,
    PriceSetInputToJSON,
} from './PriceSetInput';
import type { TaxLineInput } from './TaxLineInput';
import {
    TaxLineInputFromJSON,
    TaxLineInputFromJSONTyped,
    TaxLineInputToJSON,
} from './TaxLineInput';

/**
 * 
 * @export
 * @interface OrderLineInput
 */
export interface OrderLineInput {
    /**
     * 
     * @type {number}
     * @memberof OrderLineInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof OrderLineInput
     */
    sku: string;
    /**
     * 
     * @type {string}
     * @memberof OrderLineInput
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof OrderLineInput
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof OrderLineInput
     */
    variantId: number;
    /**
     * 
     * @type {string}
     * @memberof OrderLineInput
     */
    variantTitle?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderLineInput
     */
    quantity: number;
    /**
     * 
     * @type {PriceSetInput}
     * @memberof OrderLineInput
     */
    priceSet: PriceSetInput;
    /**
     * 
     * @type {PriceSetInput}
     * @memberof OrderLineInput
     */
    totalDiscountSet: PriceSetInput;
    /**
     * 
     * @type {Array<TaxLineInput>}
     * @memberof OrderLineInput
     */
    taxLines: Array<TaxLineInput>;
}

/**
 * Check if a given object implements the OrderLineInput interface.
 */
export function instanceOfOrderLineInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "sku" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "productId" in value;
    isInstance = isInstance && "variantId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "priceSet" in value;
    isInstance = isInstance && "totalDiscountSet" in value;
    isInstance = isInstance && "taxLines" in value;

    return isInstance;
}

export function OrderLineInputFromJSON(json: any): OrderLineInput {
    return OrderLineInputFromJSONTyped(json, false);
}

export function OrderLineInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderLineInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sku': json['sku'],
        'title': json['title'],
        'productId': json['product_id'],
        'variantId': json['variant_id'],
        'variantTitle': !exists(json, 'variant_title') ? undefined : json['variant_title'],
        'quantity': json['quantity'],
        'priceSet': PriceSetInputFromJSON(json['price_set']),
        'totalDiscountSet': PriceSetInputFromJSON(json['total_discount_set']),
        'taxLines': ((json['tax_lines'] as Array<any>).map(TaxLineInputFromJSON)),
    };
}

export function OrderLineInputToJSON(value?: OrderLineInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sku': value.sku,
        'title': value.title,
        'product_id': value.productId,
        'variant_id': value.variantId,
        'variant_title': value.variantTitle,
        'quantity': value.quantity,
        'price_set': PriceSetInputToJSON(value.priceSet),
        'total_discount_set': PriceSetInputToJSON(value.totalDiscountSet),
        'tax_lines': ((value.taxLines as Array<any>).map(TaxLineInputToJSON)),
    };
}

