/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MoneyInput } from './MoneyInput';
import {
    MoneyInputFromJSON,
    MoneyInputFromJSONTyped,
    MoneyInputToJSON,
} from './MoneyInput';

/**
 * 
 * @export
 * @interface PriceSetInput
 */
export interface PriceSetInput {
    /**
     * 
     * @type {MoneyInput}
     * @memberof PriceSetInput
     */
    shopMoney: MoneyInput;
    /**
     * 
     * @type {MoneyInput}
     * @memberof PriceSetInput
     */
    presentmentMoney: MoneyInput;
}

/**
 * Check if a given object implements the PriceSetInput interface.
 */
export function instanceOfPriceSetInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shopMoney" in value;
    isInstance = isInstance && "presentmentMoney" in value;

    return isInstance;
}

export function PriceSetInputFromJSON(json: any): PriceSetInput {
    return PriceSetInputFromJSONTyped(json, false);
}

export function PriceSetInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceSetInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shopMoney': MoneyInputFromJSON(json['shop_money']),
        'presentmentMoney': MoneyInputFromJSON(json['presentment_money']),
    };
}

export function PriceSetInputToJSON(value?: PriceSetInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shop_money': MoneyInputToJSON(value.shopMoney),
        'presentment_money': MoneyInputToJSON(value.presentmentMoney),
    };
}

