/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProductStatusOutput = {
    Active: 'ACTIVE',
    Archived: 'ARCHIVED',
    Draft: 'DRAFT'
} as const;
export type ProductStatusOutput = typeof ProductStatusOutput[keyof typeof ProductStatusOutput];


export function ProductStatusOutputFromJSON(json: any): ProductStatusOutput {
    return ProductStatusOutputFromJSONTyped(json, false);
}

export function ProductStatusOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductStatusOutput {
    return json as ProductStatusOutput;
}

export function ProductStatusOutputToJSON(value?: ProductStatusOutput | null): any {
    return value as any;
}

