/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductStatusOutput } from './ProductStatusOutput';
import {
    ProductStatusOutputFromJSON,
    ProductStatusOutputFromJSONTyped,
    ProductStatusOutputToJSON,
} from './ProductStatusOutput';
import type { ProductVariantOutput } from './ProductVariantOutput';
import {
    ProductVariantOutputFromJSON,
    ProductVariantOutputFromJSONTyped,
    ProductVariantOutputToJSON,
} from './ProductVariantOutput';

/**
 * 
 * @export
 * @interface ProductOutput
 */
export interface ProductOutput {
    /**
     * 
     * @type {number}
     * @memberof ProductOutput
     */
    shopifyId: number;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    handle: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    vendor: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    productType: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductOutput
     */
    mainImageUrl: string;
    /**
     * 
     * @type {ProductStatusOutput}
     * @memberof ProductOutput
     */
    status: ProductStatusOutput;
    /**
     * 
     * @type {Date}
     * @memberof ProductOutput
     */
    createdDateTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductOutput
     */
    updatedDateTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductOutput
     */
    publishedDateTime?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductOutput
     */
    tags: Array<string>;
    /**
     * 
     * @type {Array<ProductVariantOutput>}
     * @memberof ProductOutput
     */
    variants: Array<ProductVariantOutput>;
}

/**
 * Check if a given object implements the ProductOutput interface.
 */
export function instanceOfProductOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shopifyId" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "handle" in value;
    isInstance = isInstance && "vendor" in value;
    isInstance = isInstance && "productType" in value;
    isInstance = isInstance && "mainImageUrl" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdDateTime" in value;
    isInstance = isInstance && "updatedDateTime" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "variants" in value;

    return isInstance;
}

export function ProductOutputFromJSON(json: any): ProductOutput {
    return ProductOutputFromJSONTyped(json, false);
}

export function ProductOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shopifyId': json['shopify_id'],
        'title': json['title'],
        'handle': json['handle'],
        'vendor': json['vendor'],
        'productType': json['product_type'],
        'mainImageUrl': json['main_image_url'],
        'status': ProductStatusOutputFromJSON(json['status']),
        'createdDateTime': json['created_date_time'],
        'updatedDateTime': json['updated_date_time'],
        'publishedDateTime': !exists(json, 'published_date_time') ? undefined : json['published_date_time'],
        'tags': json['tags'],
        'variants': ((json['variants'] as Array<any>).map(ProductVariantOutputFromJSON)),
    };
}

export function ProductOutputToJSON(value?: ProductOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shopify_id': value.shopifyId,
        'title': value.title,
        'handle': value.handle,
        'vendor': value.vendor,
        'product_type': value.productType,
        'main_image_url': value.mainImageUrl,
        'status': ProductStatusOutputToJSON(value.status),
        'created_date_time': value.createdDateTime,
        'updated_date_time': value.updatedDateTime,
        'published_date_time': value.publishedDateTime,
        'tags': value.tags,
        'variants': ((value.variants as Array<any>).map(ProductVariantOutputToJSON)),
    };
}

