/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductImageInput
 */
export interface ProductImageInput {
    /**
     * 
     * @type {number}
     * @memberof ProductImageInput
     */
    position: number;
    /**
     * 
     * @type {string}
     * @memberof ProductImageInput
     */
    src: string;
}

/**
 * Check if a given object implements the ProductImageInput interface.
 */
export function instanceOfProductImageInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "position" in value;
    isInstance = isInstance && "src" in value;

    return isInstance;
}

export function ProductImageInputFromJSON(json: any): ProductImageInput {
    return ProductImageInputFromJSONTyped(json, false);
}

export function ProductImageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImageInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'position': json['position'],
        'src': json['src'],
    };
}

export function ProductImageInputToJSON(value?: ProductImageInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'position': value.position,
        'src': value.src,
    };
}

