/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProductStatusInput = {
    Active: 'ACTIVE',
    Archived: 'ARCHIVED',
    Draft: 'DRAFT'
} as const;
export type ProductStatusInput = typeof ProductStatusInput[keyof typeof ProductStatusInput];


export function ProductStatusInputFromJSON(json: any): ProductStatusInput {
    return ProductStatusInputFromJSONTyped(json, false);
}

export function ProductStatusInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductStatusInput {
    return json as ProductStatusInput;
}

export function ProductStatusInputToJSON(value?: ProductStatusInput | null): any {
    return value as any;
}

