/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductVariantInput
 */
export interface ProductVariantInput {
    /**
     * 
     * @type {number}
     * @memberof ProductVariantInput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantInput
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantInput
     */
    sku: string;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantInput
     */
    inventoryQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantInput
     */
    grams: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantInput
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantInput
     */
    compareAtPrice?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariantInput
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariantInput
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ProductVariantInput interface.
 */
export function instanceOfProductVariantInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "sku" in value;
    isInstance = isInstance && "inventoryQuantity" in value;
    isInstance = isInstance && "grams" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function ProductVariantInputFromJSON(json: any): ProductVariantInput {
    return ProductVariantInputFromJSONTyped(json, false);
}

export function ProductVariantInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariantInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'sku': json['sku'],
        'inventoryQuantity': json['inventory_quantity'],
        'grams': json['grams'],
        'price': json['price'],
        'compareAtPrice': !exists(json, 'compare_at_price') ? undefined : json['compare_at_price'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function ProductVariantInputToJSON(value?: ProductVariantInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'sku': value.sku,
        'inventory_quantity': value.inventoryQuantity,
        'grams': value.grams,
        'price': value.price,
        'compare_at_price': value.compareAtPrice,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

