/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RestockTypeInput } from './RestockTypeInput';
import {
    RestockTypeInputFromJSON,
    RestockTypeInputFromJSONTyped,
    RestockTypeInputToJSON,
} from './RestockTypeInput';

/**
 * 
 * @export
 * @interface RefundLineItemInput
 */
export interface RefundLineItemInput {
    /**
     * 
     * @type {number}
     * @memberof RefundLineItemInput
     */
    lineItemId: number;
    /**
     * 
     * @type {RestockTypeInput}
     * @memberof RefundLineItemInput
     */
    restockType: RestockTypeInput;
}

/**
 * Check if a given object implements the RefundLineItemInput interface.
 */
export function instanceOfRefundLineItemInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lineItemId" in value;
    isInstance = isInstance && "restockType" in value;

    return isInstance;
}

export function RefundLineItemInputFromJSON(json: any): RefundLineItemInput {
    return RefundLineItemInputFromJSONTyped(json, false);
}

export function RefundLineItemInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundLineItemInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineItemId': json['line_item_id'],
        'restockType': RestockTypeInputFromJSON(json['restock_type']),
    };
}

export function RefundLineItemInputToJSON(value?: RefundLineItemInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line_item_id': value.lineItemId,
        'restock_type': RestockTypeInputToJSON(value.restockType),
    };
}

