/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RefundLineItemInput } from './RefundLineItemInput';
import {
    RefundLineItemInputFromJSON,
    RefundLineItemInputFromJSONTyped,
    RefundLineItemInputToJSON,
} from './RefundLineItemInput';

/**
 * 
 * @export
 * @interface RefundInput
 */
export interface RefundInput {
    /**
     * 
     * @type {Array<RefundLineItemInput>}
     * @memberof RefundInput
     */
    refundLineItems: Array<RefundLineItemInput>;
}

/**
 * Check if a given object implements the RefundInput interface.
 */
export function instanceOfRefundInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "refundLineItems" in value;

    return isInstance;
}

export function RefundInputFromJSON(json: any): RefundInput {
    return RefundInputFromJSONTyped(json, false);
}

export function RefundInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refundLineItems': ((json['refund_line_items'] as Array<any>).map(RefundLineItemInputFromJSON)),
    };
}

export function RefundInputToJSON(value?: RefundInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refund_line_items': ((value.refundLineItems as Array<any>).map(RefundLineItemInputToJSON)),
    };
}

