/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestockTypeInput = {
    NoRestock: 'NO_RESTOCK',
    Cancel: 'CANCEL',
    Return: 'RETURN'
} as const;
export type RestockTypeInput = typeof RestockTypeInput[keyof typeof RestockTypeInput];


export function RestockTypeInputFromJSON(json: any): RestockTypeInput {
    return RestockTypeInputFromJSONTyped(json, false);
}

export function RestockTypeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestockTypeInput {
    return json as RestockTypeInput;
}

export function RestockTypeInputToJSON(value?: RestockTypeInput | null): any {
    return value as any;
}

