/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestockType = {
    Null: 'NULL',
    NoRestock: 'NO_RESTOCK',
    Cancel: 'CANCEL',
    Return: 'RETURN'
} as const;
export type RestockType = typeof RestockType[keyof typeof RestockType];


export function RestockTypeFromJSON(json: any): RestockType {
    return RestockTypeFromJSONTyped(json, false);
}

export function RestockTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestockType {
    return json as RestockType;
}

export function RestockTypeToJSON(value?: RestockType | null): any {
    return value as any;
}

