/* tslint:disable */
/* eslint-disable */
/**
 * fit-shopify-data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatsOutput
 */
export interface StatsOutput {
    /**
     * 
     * @type {Date}
     * @memberof StatsOutput
     */
    from: Date;
    /**
     * 
     * @type {Date}
     * @memberof StatsOutput
     */
    to: Date;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    numberOfOrders: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    averageOrderValue: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    totalOrderValue: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    averageShippingValue: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    totalShippingValue: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    averageOrderWeight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    totalOrderWeight: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    numberOfOrderLines: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    averageOrderLineValue: number;
    /**
     * 
     * @type {number}
     * @memberof StatsOutput
     */
    totalOrderLineValue: number;
}

/**
 * Check if a given object implements the StatsOutput interface.
 */
export function instanceOfStatsOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "numberOfOrders" in value;
    isInstance = isInstance && "averageOrderValue" in value;
    isInstance = isInstance && "totalOrderValue" in value;
    isInstance = isInstance && "averageShippingValue" in value;
    isInstance = isInstance && "totalShippingValue" in value;
    isInstance = isInstance && "totalOrderWeight" in value;
    isInstance = isInstance && "numberOfOrderLines" in value;
    isInstance = isInstance && "averageOrderLineValue" in value;
    isInstance = isInstance && "totalOrderLineValue" in value;

    return isInstance;
}

export function StatsOutputFromJSON(json: any): StatsOutput {
    return StatsOutputFromJSONTyped(json, false);
}

export function StatsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'numberOfOrders': json['number_of_orders'],
        'averageOrderValue': json['average_order_value'],
        'totalOrderValue': json['total_order_value'],
        'averageShippingValue': json['average_shipping_value'],
        'totalShippingValue': json['total_shipping_value'],
        'averageOrderWeight': !exists(json, 'average_order_weight') ? undefined : json['average_order_weight'],
        'totalOrderWeight': json['total_order_weight'],
        'numberOfOrderLines': json['number_of_order_lines'],
        'averageOrderLineValue': json['average_order_line_value'],
        'totalOrderLineValue': json['total_order_line_value'],
    };
}

export function StatsOutputToJSON(value?: StatsOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'to': value.to,
        'number_of_orders': value.numberOfOrders,
        'average_order_value': value.averageOrderValue,
        'total_order_value': value.totalOrderValue,
        'average_shipping_value': value.averageShippingValue,
        'total_shipping_value': value.totalShippingValue,
        'average_order_weight': value.averageOrderWeight,
        'total_order_weight': value.totalOrderWeight,
        'number_of_order_lines': value.numberOfOrderLines,
        'average_order_line_value': value.averageOrderLineValue,
        'total_order_line_value': value.totalOrderLineValue,
    };
}

